---
title: "Modern ignition probability"
author: "Jen Baron"
date: "February 23, 2022"
output:
  html_document:
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: "hide"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages

```{r}
library(dplyr)
library(ggplot2)
```
# All Ignitions

## Subzone

```{r}
Purcell_Ig <- read.csv("data/Ignitions_BEC_Purcell.csv") %>%
  mutate(Region = "Purcell")

KootenayS_Ig <- read.csv("data/Ignitions_BEC_Kootenay_South.csv") %>%
  mutate(Region = "Kootenay South")

KootenayN_Ig <- read.csv("data/Ignitions_BEC_Kootenay_North.csv") %>%
  mutate(Region = "Kootenay North")

Elk_Ig <- read.csv("data/Ignitions_BEC_Elk.csv") %>%
  mutate(Region = "Elk")


Columbia_Ig <- read.csv("data/Ignitions_BEC_Columbia.csv") %>%
  mutate(Region = "Columbia")
```


```{r}
Ignitions <- rbind(Purcell_Ig, KootenayS_Ig, KootenayN_Ig, Elk_Ig, Columbia_Ig) %>%
  select(Region, MAP_LABEL, AREA, MIN, MAX, MEAN, MEDIAN) %>%
  mutate_if(is.numeric, signif, 1)
```

## Subzone & Aspect

# Lightning & Unknown Ignitions

## Subzone

## Subzone & Aspect

#Save Outputs

```{r}
write.csv(Ignitions, "outputs/ignitions.csv")
```
 
# Reproducibility

```{r}
Sys.time()
git2r::repository()
sessionInfo()
```